//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_BanReservas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Persona
    {
        public int Id { get; set; }
        [StringLength (20, MinimumLength = 3)]
        public string Nombre { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat (DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime FechaDeNacimiento { get; set; }



        public bool guardar()
        {
            bool state = false;
            try
            {
                using (var con = new PruebaBrCon())
                {
                    con.Entry(this).State = System.Data.Entity.EntityState.Added;
                    con.SaveChanges();
                    state = true;
                }
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
            return state;
        }
    }

    
}
